public class Main {

    public static void main(String[] args) {
        /*
            Each new number is generated by adding the previous 2 numbers.

            Starting with 1 and 2, the first 10 numbers would be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

            (1 + 2 = 3) (2 + 3 = 5) (3 + 5 = 8) (5 + 8 = 13) (8 + 13 = 21)
            (13 + 21 = 34) (21 + 34 = 55) (34 + 55 = 89) (55 + 89 = 144) (89 + 144 = 233)

            Add the even-valued numbers together whose values
            do not exceed four million.
         */
    }
}
